x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    restart: always
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.1.1
    restart: always
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging: *default-logging

  ldes-client:
    build: https://github.com/lblod/ldes-client.git#feat/fancy-error-handling
    restart: always
    volumes:
      - ./config/ldes-client:/config
    environment:
      RUN_AT_STARTUP: true
      DELAY: 1000
      CRON_PATTERN: "*/1 * * * *"
      CRON_RETRIES: 5
      DIRECT_DATABASE_CONNECTION: "http://triplestore:8890/sparql"
      GRAPH_STORE_URL: "http://triplestore:8890/sparql-graph-crud"
      RANDOMIZE_GRAPHS: "true"
      BATCH_SIZE: 100
      AWV_BASE: "https://services.apps-tei.mow.vlaanderen.be/ldes-server/geplande-opstellingen-v1"
      AWV_FIRST_PAGE: "https://services.apps-tei.mow.vlaanderen.be/ldes-server/geplande-opstellingen-v1/by-page"
    logging: *default-logging
    labels:
      - "logging=true"

  vks:
    image: lblod/vks-design-service:0.4.1
    environment:
      MOW_ENDPOINT: 'https://roadsigns.lblod.info/sparql'
      ALLOW_MU_AUTH_SUDO: true

  resource:
    image: semtech/mu-cl-resources:1.27.2
    restart: always
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    restart: always
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    logging: *default-logging

  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    restart: always
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
    logging: *default-logging

  database:
    image: semtech/sparql-parser:0.0.15
    restart: always
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
    logging: *default-logging

  triplestore:
    image: redpencil/virtuoso:1.4.0
    restart: always
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    logging: *default-logging
