services:
  identifier:
    restart: no

  dispatcher:
    restart: no

  vendor-login:
    restart: no

  ldes-client:
    restart: no

  vks:
    restart: no

  resource:
    restart: no

  migrations:
    restart: no

  delta-notifier:
    restart: no

  database:
    restart: no

  triplestore:
    restart: no
    environment:
      ENABLE_CORS: true
